### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by B3BECb** [B3BECb/textbooks#1]
Реализовать пользователей в системе:
- [ ] Администратор;
- [x] Преподаватель;
- [ ] Ученик.

Реализовать:
- [ ] Темы;
- [ ] Учебники;
- [ ] Презентации;
- [x] Редактор текста (CKEditor);
- [ ] Редактор презентаций (ещё не выбрал);
- [ ] Редактор ограничений для учебных групп.

**Comment by B3BECb** [comment]
Задачи реализации пользователя "Ученик":
1. создать элемент темы для ученика (см. themeElement.htm). Данный элемент должен иметь только функцию просмотра информации о теме;
2. создать элемент урока для ученика (см. lessonElement.html). Данный элемент должен иметь только функцию просмотра информации о уроке/презентации;
3. создать запрос на вывод доступных ученику тем (ограничения на уроки и презентации хранятся в таблицах lessonsConstraints и presentationsConstraints );
4. разработать класс ученика (см. teacherLogick.php). Ученик обладает только возможностью просмотра доступных ему тем и уроков;
5. для увеличения безопасности ресурса, необходимо поставлять ученику отдельный ".js" файл с необходимыми ему функциями (пример: вывод информации о теме)

Вся логика навигации по страницам должна находиться в index.php!

**Comment by B3BECb** [comment]
Задачи реализации поиска тем и уроков/презентаций:
1. для преподавателя:
- реализовать в классе teacherMainMenu.php функционал поиска тем и уроков/презентаций по названию и по содержанию (содержание урока/презентации, скорее всего, будет храниться в файле index.html, который находится в директории урока/презентации)
- создать функцию поиска в ".js" файле преподавателя (используя ajax, получить информацию с сервера и вывести её на страницу).

2.. для ученика:
- реализовать в классе ученика функционал поиска тем и уроков/презентаций по названию и по содержанию (содержание урока/презентации, скорее всего, будет храниться в файле index.html, который находится в директории урока/презентации)
- создать функцию поиска в ".js" файле ученика (используя ajax, получить информацию с сервера и вывести её на страницу).
